# TCL File Generated by Component Editor 18.1
# Wed Apr 01 23:56:18 EDT 2020
# DO NOT MODIFY


# 
# himm_module_v1_0_S00_Avalon "himm_module_v1_0_S00_Avalon" v1.0
#  2020.04.01.23:56:18
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module himm_module_v1_0_S00_Avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME himm_module_v1_0_S00_Avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME himm_module_v1_0_S00_Avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL himm_module_v1_0_S00_Avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file himm_module_v1_0_S00_Avalon.v VERILOG PATH himm_module_v1_0_S00_Avalon.v


# 
# parameters
# 
add_parameter SECURE_DATA_OUT_WIDTH INTEGER 32
set_parameter_property SECURE_DATA_OUT_WIDTH DEFAULT_VALUE 32
set_parameter_property SECURE_DATA_OUT_WIDTH DISPLAY_NAME SECURE_DATA_OUT_WIDTH
set_parameter_property SECURE_DATA_OUT_WIDTH TYPE INTEGER
set_parameter_property SECURE_DATA_OUT_WIDTH UNITS None
set_parameter_property SECURE_DATA_OUT_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SECURE_DATA_OUT_WIDTH HDL_PARAMETER true
add_parameter C_S_AVALON_DATA_WIDTH INTEGER 32
set_parameter_property C_S_AVALON_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property C_S_AVALON_DATA_WIDTH DISPLAY_NAME C_S_AVALON_DATA_WIDTH
set_parameter_property C_S_AVALON_DATA_WIDTH TYPE INTEGER
set_parameter_property C_S_AVALON_DATA_WIDTH UNITS None
set_parameter_property C_S_AVALON_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S_AVALON_DATA_WIDTH HDL_PARAMETER true
add_parameter C_S_AVALON_ADDR_WIDTH INTEGER 4
set_parameter_property C_S_AVALON_ADDR_WIDTH DEFAULT_VALUE 4
set_parameter_property C_S_AVALON_ADDR_WIDTH DISPLAY_NAME C_S_AVALON_ADDR_WIDTH
set_parameter_property C_S_AVALON_ADDR_WIDTH TYPE INTEGER
set_parameter_property C_S_AVALON_ADDR_WIDTH UNITS None
set_parameter_property C_S_AVALON_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S_AVALON_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock_sink
set_interface_property s0 associatedReset reset_sink
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 S0_ADDRESS address Input C_S_AVALON_ADDR_WIDTH
add_interface_port s0 S0_WRITE write Input 1
add_interface_port s0 S0_WRITEDATA writedata Input C_S_AVALON_DATA_WIDTH
add_interface_port s0 S0_READ read Input 1
add_interface_port s0 S0_READDATA readdata Output C_S_AVALON_DATA_WIDTH
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink S0_CLK clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink S0_RESET reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end secure_data_out writeresponsevalid_n Output SECURE_DATA_OUT_WIDTH

