
CPU_parameter = [
    ["bht_ramBlockType",  "Automatic"],
    ["breakOffset",       "32"],
    ["breakSlave",        "None"],
    ["cdx_enabled",       "0"],
    ["cpuArchRev",        "1"],
    ["cpuID",             "0"],
    ["cpuReset",          "0"],
    ["data_master_high_performance_paddr_base",  "0"],
    ["data_master_high_performance_paddr_size",  "0.0"],
    ["data_master_paddr_base",  "0"],
    ["data_master_paddr_size",  "0.0"],
    ["dcache_bursts",  "false"],
    ["dcache_numTCDM",  "0"],
    ["dcache_ramBlockType",  "Automatic"],
    ["dcache_size",  "2048"],
    ["dcache_tagramBlockType",  "Automatic"],
    ["dcache_victim_buf_impl",  "ram"],
    ["debug_OCIOnchipTrace",  "_128"],
    ["debug_assignJtagInstanceID",  "0"],
    ["debug_datatrigger",  "0"],
    ["debug_debugReqSignals",  "0"],
    ["debug_enabled",  "1"],
    ["debug_hwbreakpoint",  "0"],
    ["debug_jtagInstanceID",  "0"],
    ["debug_traceStorage",  "onchip_trace"],
    ["debug_traceType",  "none"],
    ["debug_triggerArming",  "1"],
    ["dividerType",  "no_div"],
    ["exceptionOffset",  "32"],
    ["exceptionSlave",  "MEMORY1.s1"],
    ["fa_cache_line",  "2"],
    ["fa_cache_linesize",  "0"],
    ["flash_instruction_master_paddr_base",  "0"],
    ["flash_instruction_master_paddr_size",  "0.0"],
    ["icache_burstType",  "None"],
    ["icache_numTCIM",  "0"],
    ["icache_ramBlockType",  "Automatic"],
    ["icache_size",  "4096"],
    ["icache_tagramBlockType",  "Automatic"],
    ["impl",  "Fast"],
    ["instruction_master_high_performance_paddr_base",  "0"],
    ["instruction_master_high_performance_paddr_size",  "0.0"],
    ["instruction_master_paddr_base",  "0"],
    ["instruction_master_paddr_size",  "0.0"],
    ["io_regionbase",  "0"],
    ["io_regionsize",  "0"],
    ["master_addr_map",  "0"],
    ["mmu_TLBMissExcOffset",  "0"],
    ["mmu_TLBMissExcSlave",  "None"],
    ["mmu_autoAssignTlbPtrSz",  "1"],
    ["mmu_enabled",  "0"],
    ["mmu_processIDNumBits",  "8"],
    ["mmu_ramBlockType",  "Automatic"],
    ["mmu_tlbNumWays",  "16"],
    ["mmu_tlbPtrSz",  "7"],
    ["mmu_udtlbNumEntries",  "6"],
    ["mmu_uitlbNumEntries",  "4"],
    ["mpu_enabled",  "0"],
    ["mpu_minDataRegionSize",  "12"],
    ["mpu_minInstRegionSize",  "12"],
    ["mpu_numOfDataRegion",  "8"],
    ["mpu_numOfInstRegion",  "8"],
    ["mpu_useLimit",  "0"],
    ["mpx_enabled",  "0"],
    ["mul_32_impl",  "2"],
    ["mul_64_impl",  "0"],
    ["mul_shift_choice",  "0"],
    ["ocimem_ramBlockType",  "Automatic"],
    ["ocimem_ramInit",  "0"],
    ["regfile_ramBlockType",  "Automatic"],
    ["register_file_por",  "0"],
    ["resetOffset",  "0"],
    ["resetSlave",  "CPU.debug_mem_slave"],
    ["resetrequest_enabled",  "1"],
    ["setting_HBreakTest",  "0"],
    ["setting_HDLSimCachesCleared",  "1"],
    ["setting_activateMonitors",  "1"],
    ["setting_activateTestEndChecker",  "0"],
    ["setting_activateTrace",  "0"],
    ["setting_allow_break_inst",  "0"],
    ["setting_alwaysEncrypt",  "1"],
    ["setting_asic_add_scan_mode_input",  "0"],
    ["setting_asic_enabled",  "0"],
    ["setting_asic_synopsys_translate_on_off",  "0"],
    ["setting_asic_third_party_synthesis",  "0"],
    ["setting_avalonDebugPortPresent",  "0"],
    ["setting_bhtPtrSz",  "8"],
    ["setting_bigEndian",  "0"],
    ["setting_branchpredictiontype",  "Dynamic"],
    ["setting_breakslaveoveride",  "0"],
    ["setting_clearXBitsLDNonBypass",  "1"],
    ["setting_dc_ecc_present",  "1"],
    ["setting_disable_tmr_inj",  "0"],
    ["setting_disableocitrace",  "0"],
    ["setting_dtcm_ecc_present",  "1"],
    ["setting_ecc_present",  "0"],
    ["setting_ecc_sim_test_ports",  "0"],
    ["setting_exportHostDebugPort",  "0"],
    ["setting_exportPCB",  "0"],
    ["setting_export_large_RAMs",  "0"],
    ["setting_exportdebuginfo",  "0"],
    ["setting_exportvectors",  "0"],
    ["setting_fast_register_read",  "0"],
    ["setting_ic_ecc_present",  "1"],
    ["setting_interruptControllerType",  "Internal"],
    ["setting_itcm_ecc_present",  "1"],
    ["setting_mmu_ecc_present",  "1"],
    ["setting_oci_export_jtag_signals",  "0"],
    ["setting_oci_version",  "1"],
    ["setting_preciseIllegalMemAccessException",  "0"],
    ["setting_removeRAMinit",  "0"],
    ["setting_rf_ecc_present",  "1"],
    ["setting_shadowRegisterSets",  "0"],
    ["setting_showInternalSettings",  "0"],
    ["setting_showUnpublishedSettings",  "0"],
    ["setting_support31bitdcachebypass",  "1"],
    ["setting_tmr_output_disable",  "0"],
    ["setting_usedesignware",  "0"],
    ["shift_rot_impl",  "1"],
    ["tightly_coupled_data_master_0_paddr_base",  "0"],
    ["tightly_coupled_data_master_0_paddr_size",  "0.0"],
    ["tightly_coupled_data_master_1_paddr_base",  "0"],
    ["tightly_coupled_data_master_1_paddr_size",  "0.0"],
    ["tightly_coupled_data_master_2_paddr_base",  "0"],
    ["tightly_coupled_data_master_2_paddr_size",  "0.0"],
    ["tightly_coupled_data_master_3_paddr_base",  "0"],
    ["tightly_coupled_data_master_3_paddr_size",  "0.0"],
    ["tightly_coupled_instruction_master_0_paddr_base",  "0"],
    ["tightly_coupled_instruction_master_0_paddr_size",  "0.0"],
    ["tightly_coupled_instruction_master_1_paddr_base",  "0"],
    ["tightly_coupled_instruction_master_1_paddr_size",  "0.0"],
    ["tightly_coupled_instruction_master_2_paddr_base",  "0"],
    ["tightly_coupled_instruction_master_2_paddr_size",  "0.0"],
    ["tightly_coupled_instruction_master_3_paddr_base",  "0"],
    ["tightly_coupled_instruction_master_3_paddr_size",  "0.0"],
    ["tmr_enabled",  "0"],
    ["tracefilename", ""],
    ["userDefinedSettings", ""]
]

GPIO_parameter = [
    ["bitClearingEdgeCapReg",  "0"],
    ["bitModifyingOutReg",  "0"],
    ["captureEdge",  "0"],
    ["direction",  "Output"],
    ["edgeType",  "RISING"],
    ["generateIRQ",  "0"],
    ["irqType",  "LEVEL"],
    ["resetValue",  "0.0"],
    ["simDoTestBenchWiring",  "0"],
    ["simDrivenValue",  "0.0"],
    ["width",  "8"]
]

MEMORY_parameter = [
    ["allowInSystemMemoryContentEditor",  "0"],
    ["blockType",  "AUTO"],
    ["copyInitFile",  "0"],
    ["dataWidth",  "32"],
    ["dataWidth2",  "32"],
    ["dualPort",  "0"],
    ["ecc_enabled",  "0"],
    ["enPRInitMode",  "0"],
    ["enableDiffWidth",  "0"],
    ["initMemContent",  "1"],
    ["initializationFileName",  "onchip_mem.hex"],
    ["instanceID",  "NONE"],
    ["memorySize",  "409600.0"],
    ["readDuringWriteMode",  "DONT_CARE"],
    ["resetrequest_enabled",  "1"],
    ["simAllowMRAMContentsFile",  "0"],
    ["simMemInitOnlyFilename",  "0"],
    ["singleClockOperation",  "0"],
    ["slave1Latency",  "1"],
    ["slave2Latency",  "1"],
    ["useNonDefaultInitFile",  "0"],
    ["useShallowMemBlocks",  "0"],
    ["writable",  "1"]
]

CLOCK_parameter = [
    ["clockFrequency", "50000000.0"],
    ["clockFrequencyKnown", "1"],
    ["resetSynchronousEdges", "NONE"]
]

JTAG_parameter = [
    ["allowMultipleConnections",  "0"],
    ["hubInstanceID",  "0"],
    ["readBufferDepth",  "64"],
    ["readIRQThreshold",  "8"],
    ["simInputCharacterStream",  ""],
    ["simInteractiveOptions",  "NO_INTERACTIVE_WINDOWS"],
    ["useRegistersForReadBuffer",  "0"],
    ["useRegistersForWriteBuffer",  "0"],
    ["useRelativePathForSimFile",  "0"],
    ["writeBufferDepth",  "64"],
    ["writeIRQThreshold",  "8"]
]

DATA_baseAddress = [
    ["CPU.debug_mem_slave", "0x00100800"],
    ["GPIO.s1", "0x00100840"],              # previous value : 0x00101000
    ["MEMORY1.s1", "0x00100000"],           # previous value : 0x00080000
    ["jtag_uart_0.avalon_jtag_slave", "0x00100010"], # previous value : 0x00101010
    ["himm_module_v1_0_S00_Avalon_0.s0",   "0x0000"]
]

INSTRUCTION_baseAddress = [
    ["CPU.debug_mem_slave", "0x00100800"],
    ["MEMORY1.s1",  "0x00080000"]
]

HIMM_parameter = [
    ["C_S_AVALON_ADDR_WIDTH",   "4"],
    ["C_S_AVALON_DATA_WIDTH",   "32"],
    ["SECURE_DATA_OUT_WIDTH",   "32"]
]
